### ISSUE TITLE
Boxer closes the application main window on OS X 

### ISSUE THREAD

**Issue by ithron** [aaronmjacobs/Boxer#4]
When boxer::show() is called either from applicationDidFinishLaunching: or from windowWillClose: the message window appear only for a very short moment and then disappears again, together with the applications main window. Commenting out the two lines that should force the alert on top of all other windows fixes the issue.
See my commit [b061874f8abfc2e89a437aff33923e05731dd996](https://github.com/ithron/Boxer/commit/b061874f8abfc2e89a437aff33923e05731dd996)

**Comment by aaronmjacobs** [comment]
Hm, that's unfortunate. Those two lines were my only successful attempt at forcing the alert to appear on top of other windows. I'll do some more investigating.

**Comment by aaronmjacobs** [comment]
I know this is a bit late, but I may have a fix - feel free to check out the new code, and let me know if it works better for you!

dde9f3685581540241989deba4b10951c644bbeb

**Comment by aaronmjacobs** [comment]
Going to close this, as I believe it should be fixed.
