### ISSUE TITLE
CMAKE generates a 32 bit only project

### ISSUE THREAD

**Issue by ghost** [aaronmjacobs/Boxer#5]
Compiling the files generated by CMAKE lead to a 32 bit only build, there is no option to change the build to x64.

**Comment by aaronmjacobs** [comment]
When configuring the project with CMake, you should be able to select a 64 bit generator (here's an example using the CMake GUI on Windows):

![image](https://cloud.githubusercontent.com/assets/1409522/26036802/e7404992-3899-11e7-9b31-024c4ca37c18.png)
