### ISSUE TITLE
File update request

### ISSUE THREAD

**Issue by hyperdregon** [aaronmjacobs/Boxer#9]
Update of boxer_win.cpp

(Bug fix)

`
#include <boxer/boxer.h>
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <Windows.h>

namespace boxer {

namespace {

UINT getIcon(Style style) {
   switch (style) {
      case Style::Info:
         return MB_ICONINFORMATION;
      case Style::Warning:
         return MB_ICONWARNING;
      case Style::Error:
         return MB_ICONERROR;
      case Style::Question:
         return MB_ICONQUESTION;
      default:
         return MB_ICONINFORMATION;
   }
}

UINT getButtons(Buttons buttons) {
   switch (buttons) {
      case Buttons::OK:
      case Buttons::Quit: // There is no 'Quit' button on Windows :(
         return MB_OK;
      case Buttons::OKCancel:
         return MB_OKCANCEL;
      case Buttons::YesNo:
         return MB_YESNO;
      default:
         return MB_OK;
   }
}

Selection getSelection(int response, Buttons buttons) {
   switch (response) {
      case IDOK:
         return buttons == Buttons::Quit ? Selection::Quit : Selection::OK;
      case IDCANCEL:
         return Selection::Cancel;
      case IDYES:
         return Selection::Yes;
      case IDNO:
         return Selection::No;
      default:
         return Selection::None;
   }
}

} // namespace

Selection show(const char *message, const char *title, Style style, Buttons buttons) {
   UINT flags = MB_TASKMODAL;

   flags |= getIcon(style);
   flags |= getButtons(buttons);

   return getSelection(MessageBoxA(nullptr, message, title, flags), buttons);
}

} // namespace boxer
`

**Comment by aaronmjacobs** [comment]
Thanks for the suggestion! Could you submit the code change as a pull request?

Thanks!

**Comment by ExileFox** [comment]
But **what** does this fix?

**Comment by ExileFox** [comment]
please explain what the change does ???

**Comment by aaronmjacobs** [comment]
The change swapped the call from `MessageBox` to `MessageBoxA` (the ASCII variant). As of d872cd24d3068f8ac8a10dd1df3f2239ccd1747c and 8f6b579c15747fa5a035a0d25a92eeccc0a0ed5f the code supports UTF-8, making the suggested change no longer relevant.

**Comment by ExileFox** [comment]
Okay thanks for the explanation.
